In [ ]:
### MULTI-STOCK FINANCIAL SENTIMENT ANALYSIS PROJECT

In [ ]:
!pip install transformers
!pip install nltk
!pip install beautifulsoup4
!pip install requests
!pip install plotly
!pip install streamlit
!pip install openpyxl

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.4.22)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.1)
Collecting streamlit
  Downloading streamlit-1.57.0-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.3)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.47)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.1)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.46.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.26)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.20.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.13)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.4.22)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.57.0-py3-none-any.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 51.9 MB/s eta 0:00:00
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 82.5 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.2 streamlit-1.57.0
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [ ]:
import pandas as pd

import requests

from bs4 import BeautifulSoup

import nltk

import re

import time

from datetime import datetime

import matplotlib.pyplot as plt

In [ ]:
stocks = [

    ['Technology – Semiconductor & AI Industry', 'NVDA', 'NVIDIA'],

    ['Technology – Semiconductor & AI Industry', 'AMD', 'Advanced Micro Devices'],

    ['Technology – Semiconductor & AI Industry', 'INTC', 'Intel'],

    ['Financial Services – Banking & FinTech', 'JPM', 'JPMorgan Chase'],

    ['Financial Services – Banking & FinTech', 'BAC', 'Bank of America'],

    ['Financial Services – Banking & FinTech', 'GS', 'Goldman Sachs'],

    ['Energy – Oil & Gas Industry', 'XOM', 'Exxon Mobil'],

    ['Energy – Oil & Gas Industry', 'CVX', 'Chevron'],

    ['Energy – Oil & Gas Industry', 'COP', 'ConocoPhillips'],

    ['Healthcare – Pharma & Biotechnology', 'PFE', 'Pfizer'],

    ['Healthcare – Pharma & Biotechnology', 'JNJ', 'Johnson & Johnson'],

    ['Healthcare – Pharma & Biotechnology', 'MRK', 'Merck & Co.'],

    ['Consumer & E-Commerce Industry', 'AMZN', 'Amazon'],

    ['Consumer & E-Commerce Industry', 'WMT', 'Walmart'],

    ['Consumer & E-Commerce Industry', 'COST', 'Costco Wholesale'],

    ['Crypto', 'BTCUSD', 'Bitcoin'],

    ['Crypto', 'ETHUSD', 'Ethereum']

]

In [ ]:
news_data = []

In [ ]:
for stock in stocks:

    print(stock)

['Technology – Semiconductor & AI Industry', 'NVDA', 'NVIDIA']
['Technology – Semiconductor & AI Industry', 'AMD', 'Advanced Micro Devices']
['Technology – Semiconductor & AI Industry', 'INTC', 'Intel']
['Financial Services – Banking & FinTech', 'JPM', 'JPMorgan Chase']
['Financial Services – Banking & FinTech', 'BAC', 'Bank of America']
['Financial Services – Banking & FinTech', 'GS', 'Goldman Sachs']
['Energy – Oil & Gas Industry', 'XOM', 'Exxon Mobil']
['Energy – Oil & Gas Industry', 'CVX', 'Chevron']
['Energy – Oil & Gas Industry', 'COP', 'ConocoPhillips']
['Healthcare – Pharma & Biotechnology', 'PFE', 'Pfizer']
['Healthcare – Pharma & Biotechnology', 'JNJ', 'Johnson & Johnson']
['Healthcare – Pharma & Biotechnology', 'MRK', 'Merck & Co.']
['Consumer & E-Commerce Industry', 'AMZN', 'Amazon']
['Consumer & E-Commerce Industry', 'WMT', 'Walmart']
['Consumer & E-Commerce Industry', 'COST', 'Costco Wholesale']
['Crypto', 'BTCUSD', 'Bitcoin']
['Crypto', 'ETHUSD', 'Ethereum']

In [ ]:
for stock in stocks:

    industry = stock[0]

    ticker = stock[1]

    company_name = stock[2]

    print(industry)

    print(ticker)

    print(company_name)

Technology – Semiconductor & AI Industry
NVDA
NVIDIA
Technology – Semiconductor & AI Industry
AMD
Advanced Micro Devices
Technology – Semiconductor & AI Industry
INTC
Intel
Financial Services – Banking & FinTech
JPM
JPMorgan Chase
Financial Services – Banking & FinTech
BAC
Bank of America
Financial Services – Banking & FinTech
GS
Goldman Sachs
Energy – Oil & Gas Industry
XOM
Exxon Mobil
Energy – Oil & Gas Industry
CVX
Chevron
Energy – Oil & Gas Industry
COP
ConocoPhillips
Healthcare – Pharma & Biotechnology
PFE
Pfizer
Healthcare – Pharma & Biotechnology
JNJ
Johnson & Johnson
Healthcare – Pharma & Biotechnology
MRK
Merck & Co.
Consumer & E-Commerce Industry
AMZN
Amazon
Consumer & E-Commerce Industry
WMT
Walmart
Consumer & E-Commerce Industry
COST
Costco Wholesale
Crypto
BTCUSD
Bitcoin
Crypto
ETHUSD
Ethereum

In [ ]:
for stock in stocks:

    ticker = stock[1]

    # Crypto URL
    if ticker in ['BTCUSD', 'ETHUSD']:

        url = f"https://finviz.com/crypto_charts.ashx?t={ticker}&p=d"

    # Stock URL
    else:

        url = f"https://finviz.com/quote.ashx?t={ticker}"

    print(url)

https://finviz.com/quote.ashx?t=NVDA
https://finviz.com/quote.ashx?t=AMD
https://finviz.com/quote.ashx?t=INTC
https://finviz.com/quote.ashx?t=JPM
https://finviz.com/quote.ashx?t=BAC
https://finviz.com/quote.ashx?t=GS
https://finviz.com/quote.ashx?t=XOM
https://finviz.com/quote.ashx?t=CVX
https://finviz.com/quote.ashx?t=COP
https://finviz.com/quote.ashx?t=PFE
https://finviz.com/quote.ashx?t=JNJ
https://finviz.com/quote.ashx?t=MRK
https://finviz.com/quote.ashx?t=AMZN
https://finviz.com/quote.ashx?t=WMT
https://finviz.com/quote.ashx?t=COST
https://finviz.com/crypto_charts.ashx?t=BTCUSD&p=d
https://finviz.com/crypto_charts.ashx?t=ETHUSD&p=d

In [ ]:
headers = {

    "User-Agent": (
        "Mozilla/5.0 "
        "(Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 "
        "(KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    )
}

print(headers)

{'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}

In [ ]:
response = requests.get(

    url,

    headers=headers
)

print(response.status_code)

200

In [ ]:
soup = BeautifulSoup(

    response.text,

    'html.parser'
)

print(type(soup))

<class 'bs4.BeautifulSoup'>

In [ ]:
news_table = soup.find(

    'table',

    id='news-table'
)

print(news_table)

<table border="0" cellpadding="1" cellspacing="0" class="fullview-news-outer news-table" id="news-table" width="100%">
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/tech/2026/05/16/the-usd293-million-kelpdao-hack-shows-why-defi-is-finally-being-forced-to-grow-up');">
<td align="right" width="130">
            May-16-26 09:00AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/tech/2026/05/16/the-usd293-million-kelpdao-hack-shows-why-defi-is-finally-being-forced-to-grow-up" rel="nofollow" target="_blank">The $293 million KelpDAO hack shows why DeFi is finally being forced to grow up</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/tech/2026/05/13/the-protocol-solana-s-alpenglow-upgrade-is-live-for-testing');">
<td align="right" width="130">
            May-13-26 12:48PM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/tech/2026/05/13/the-protocol-solana-s-alpenglow-upgrade-is-live-for-testing" rel="nofollow" target="_blank">The Protocol: Solana’s ‘Alpenglow’ upgrade is live for testing</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/tech/2026/05/12/the-ethereum-foundation-unveils-new-clear-signing-standard-to-stop-users-from-approving-malicious-crypto-transactions');">
<td align="right" width="130">
            May-12-26 01:31PM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/tech/2026/05/12/the-ethereum-foundation-unveils-new-clear-signing-standard-to-stop-users-from-approving-malicious-crypto-transactions" rel="nofollow" target="_blank">The Ethereum Foundation unveils new 'Clear Signing' standard to stop users from approving malicious crypto transactions</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/markets/2026/05/12/eth-btc-ratio-falls-to-10-month-low-as-ether-continues-to-underperform-bitcoin');">
<td align="right" width="130">
            06:20AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/markets/2026/05/12/eth-btc-ratio-falls-to-10-month-low-as-ether-continues-to-underperform-bitcoin" rel="nofollow" target="_blank">ETH/BTC ratio falls to 10-month low as ether continues to underperform bitcoin</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/business/2026/05/11/galaxy-digital-to-manage-sharplink-s-new-usd125-million-onchain-yield-play');">
<td align="right" width="130">
            05:17AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/business/2026/05/11/galaxy-digital-to-manage-sharplink-s-new-usd125-million-onchain-yield-play" rel="nofollow" target="_blank">Galaxy Digital to manage Sharplink’s new $125 million onchain yield play</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/business/2026/05/11/tom-lee-s-bitmine-slows-down-ether-purchases-after-already-buying-1-million-tokens-this-year');">
<td align="right" width="130">
            May-11-26 08:56AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/business/2026/05/11/tom-lee-s-bitmine-slows-down-ether-purchases-after-already-buying-1-million-tokens-this-year" rel="nofollow" target="_blank">Tom Lee's Bitmine slows down ether purchases after already buying 1 million tokens this year</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/tech/2026/05/11/ronin-set-to-transition-to-ethereum-layer-2-from-independent-sidechain');">
<td align="right" width="130">
            08:11AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/tech/2026/05/11/ronin-set-to-transition-to-ethereum-layer-2-from-independent-sidechain" rel="nofollow" target="_blank">Ronin set to transition to Ethereum layer 2 from independent sidechain</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CryptoSlate', 'https://cryptoslate.com/blackrock-files-sidestep-clarity-yield-issues-with-two-new-tokenized-money-market-funds/');">
<td align="right" width="130">
            May-10-26 06:00AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://cryptoslate.com/blackrock-files-sidestep-clarity-yield-issues-with-two-new-tokenized-money-market-funds/" rel="nofollow" target="_blank">BlackRock looks to sidestep Clarity yield issues, filing for two new tokenized money market funds</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CryptoSlate)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/policy/2026/05/09/judge-clears-path-for-aave-to-move-usd71-million-in-eth-linked-to-north-korea-hack');">
<td align="right" width="130">
            May-09-26 12:16AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/policy/2026/05/09/judge-clears-path-for-aave-to-move-usd71-million-in-eth-linked-to-north-korea-hack" rel="nofollow" target="_blank">Judge clears path for Aave to move $71 million in ETH linked to North Korea hack</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/business/2026/05/07/bitmine-to-slow-down-ether-purchases-as-it-nears-accumulation-goal-tom-lee-says');">
<td align="right" width="130">
            May-07-26 02:17PM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/business/2026/05/07/bitmine-to-slow-down-ether-purchases-as-it-nears-accumulation-goal-tom-lee-says" rel="nofollow" target="_blank">Bitmine to slow down ether purchases as it nears accumulation goal, Tom Lee says</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/tech/2026/05/07/jaredfromsubway-bot-front-runs-vitalik-buterin-s-usd4-token-swap-with-usd1-million-in-volume');">
<td align="right" width="130">
            09:58AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/tech/2026/05/07/jaredfromsubway-bot-front-runs-vitalik-buterin-s-usd4-token-swap-with-usd1-million-in-volume" rel="nofollow" target="_blank">'JaredfromSubway' bot front runs Vitalik Buterin's $4 token swap with $1 million in volume</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/tech/2026/05/06/the-end-of-ads-coinbase-engineer-says-ai-agents-could-kill-the-internet-s-favorite-business-model');">
<td align="right" width="130">
            May-06-26 12:44PM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/tech/2026/05/06/the-end-of-ads-coinbase-engineer-says-ai-agents-could-kill-the-internet-s-favorite-business-model" rel="nofollow" target="_blank">The end of ads: Coinbase engineer says AI agents could kill the internet’s favorite business model</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/tech/2026/05/06/the-protocol-ai-agents-form-their-own-firm');">
<td align="right" width="130">
            11:18AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/tech/2026/05/06/the-protocol-ai-agents-form-their-own-firm" rel="nofollow" target="_blank">The Protocol: AI Agents form their own firm</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CryptoSlate', 'https://cryptoslate.com/ethereums-biggest-staker-has-just-become-a-public-company-with-over-10-billion-locked-up/');">
<td align="right" width="130">
            May-05-26 11:15AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://cryptoslate.com/ethereums-biggest-staker-has-just-become-a-public-company-with-over-10-billion-locked-up/" rel="nofollow" target="_blank">Ethereum’s biggest staker has just become a public company with over $10 billion locked up</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CryptoSlate)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/business/2026/05/04/tom-lee-says-crypto-spring-started-as-largest-ethereum-treasury-buys-usd238-million-in-ether');">
<td align="right" width="130">
            May-04-26 10:23AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/business/2026/05/04/tom-lee-says-crypto-spring-started-as-largest-ethereum-treasury-buys-usd238-million-in-ether" rel="nofollow" target="_blank">Tom Lee says 'crypto spring' started as largest Ethereum treasury buys $238 million in ether</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/business/2026/05/01/ethereum-foundation-finalizes-sale-of-10-000-ether-to-bitmine-as-part-of-its-treasury-strategy');">
<td align="right" width="130">
            May-01-26 02:16PM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/business/2026/05/01/ethereum-foundation-finalizes-sale-of-10-000-ether-to-bitmine-as-part-of-its-treasury-strategy" rel="nofollow" target="_blank">Ethereum Foundation finalizes sale of 10,000 ether to BitMine as part of its treasury strategy</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/tech/2026/04/29/the-protocol-mythos-forces-crypto-industry-to-rethink-security-practices');">
<td align="right" width="130">
            Apr-29-26 11:57AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/tech/2026/04/29/the-protocol-mythos-forces-crypto-industry-to-rethink-security-practices" rel="nofollow" target="_blank">The Protocol: Mythos forces crypto industry to rethink security practices</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/tech/2026/04/28/a-crypto-coalition-releases-technical-proposal-to-save-aave-users-from-a-massive-token-exploit');">
<td align="right" width="130">
            Apr-28-26 11:43AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/tech/2026/04/28/a-crypto-coalition-releases-technical-proposal-to-save-aave-users-from-a-massive-token-exploit" rel="nofollow" target="_blank">A crypto coalition releases technical proposal to save Aave users from a massive token exploit</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/tech/2026/04/27/industry-leaders-are-pouring-hundreds-of-millions-into-a-rescue-plan-for-aave-users-after-massive-crypto-hack');">
<td align="right" width="130">
            Apr-27-26 05:40PM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/tech/2026/04/27/industry-leaders-are-pouring-hundreds-of-millions-into-a-rescue-plan-for-aave-users-after-massive-crypto-hack" rel="nofollow" target="_blank">Industry leaders are pouring hundreds of millions into a rescue plan for Aave users after massive crypto hack</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/markets/2026/04/27/fidelity-digital-assets-says-bitcoin-is-leading-crypto-market-stabilization');">
<td align="right" width="130">
            11:44AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/markets/2026/04/27/fidelity-digital-assets-says-bitcoin-is-leading-crypto-market-stabilization" rel="nofollow" target="_blank">Fidelity Digital Assets says bitcoin is leading crypto market stabilization</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/business/2026/04/27/bitmine-buys-usd236-million-in-ether-as-tom-lee-touts-eth-as-wartime-store-of-value');">
<td align="right" width="130">
            09:17AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/business/2026/04/27/bitmine-buys-usd236-million-in-ether-as-tom-lee-touts-eth-as-wartime-store-of-value" rel="nofollow" target="_blank">Bitmine buys $236 million in ether as Tom Lee touts ETH as 'wartime store of value'</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/business/2026/04/26/aave-raises-nearly-80-of-the-usd200-million-it-needs-to-cover-bad-debt-left-by-kelp-dao-exploit');">
<td align="right" width="130">
            Apr-26-26 12:21PM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/business/2026/04/26/aave-raises-nearly-80-of-the-usd200-million-it-needs-to-cover-bad-debt-left-by-kelp-dao-exploit" rel="nofollow" target="_blank">Aave raises nearly 80% of the $200 million it needs to cover bad debt left by Kelp DAO exploit</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CryptoSlate', 'https://cryptoslate.com/ethereums-4-consecutive-week-rallies-fuel-bullish-bets-of-3200/');">
<td align="right" width="130">
            Apr-24-26 04:05PM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://cryptoslate.com/ethereums-4-consecutive-week-rallies-fuel-bullish-bets-of-3200/" rel="nofollow" target="_blank">Ethereum’s 4 consecutive weeks of price rallies fuel bullish bets of $3200</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CryptoSlate)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/business/2026/04/24/bitmine-to-buy-10-000-ether-for-usd23-8-million-from-the-ethereum-foundation');">
<td align="right" width="130">
            11:47AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/business/2026/04/24/bitmine-to-buy-10-000-ether-for-usd23-8-million-from-the-ethereum-foundation" rel="nofollow" target="_blank">Bitmine to buy 10,000 ether for $23.9 million from the Ethereum Foundation</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/business/2026/04/23/aave-rallies-defi-partners-to-contain-fallout-from-usd292-million-kelpdao-hack');">
<td align="right" width="130">
            Apr-23-26 04:52PM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/business/2026/04/23/aave-rallies-defi-partners-to-contain-fallout-from-usd292-million-kelpdao-hack" rel="nofollow" target="_blank">Aave rallies DeFi partners to contain fallout from $292 million KelpDAO hack</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CryptoSlate', 'https://cryptoslate.com/cardano-development-teams-wants-almost-50-million-for-bitcoin-defi-and-vision-2030/');">
<td align="right" width="130">
            03:10PM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://cryptoslate.com/cardano-development-teams-wants-almost-50-million-for-bitcoin-defi-and-vision-2030/" rel="nofollow" target="_blank">Cardano development teams wants almost $50 million for Bitcoin DeFi and Vision 2030</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CryptoSlate)</span></div></div></td></tr>
<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/tech/2026/04/22/inside-the-usd71-million-freeze-on-arbitrum-that-has-the-crypto-world-questioning-what-decentralization-really-means');">
<td align="right" width="130">
            02:35PM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">

In [ ]:
rows = news_table.findAll('tr')

print(len(rows))

100

/tmp/ipykernel_5055/3693162761.py:1: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  rows = news_table.findAll('tr')

In [ ]:
print(rows[0])

<tr class="cursor-pointer has-label" onclick="trackAndOpenNews(event, 'CoinDesk', 'https://www.coindesk.com/tech/2026/05/16/the-usd293-million-kelpdao-hack-shows-why-defi-is-finally-being-forced-to-grow-up');">
<td align="right" width="130">
            May-16-26 09:00AM
        </td>
<td align="left">
<div class="news-link-container">
<div class="news-link-left">
<a class="tab-link-news" href="https://www.coindesk.com/tech/2026/05/16/the-usd293-million-kelpdao-hack-shows-why-defi-is-finally-being-forced-to-grow-up" rel="nofollow" target="_blank">The $293 million KelpDAO hack shows why DeFi is finally being forced to grow up</a>
</div>
<div class="news-link-right flex gap-1 items-center">
<span>(CoinDesk)</span></div></div></td></tr>

In [ ]:
headline = rows[0].a.text.strip().lower()

print(headline)

the $293 million kelpdao hack shows why defi is finally being forced to grow up

In [ ]:
news_url = rows[0].a.get('href')

print(news_url)

https://www.coindesk.com/tech/2026/05/16/the-usd293-million-kelpdao-hack-shows-why-defi-is-finally-being-forced-to-grow-up

In [ ]:
source = rows[0].span.text.strip().lower()

print(source)

(coindesk)

In [ ]:
source = re.sub(

    r"[()]",

    "",

    source
)

print(source)

coindesk

In [ ]:
news_url = rows[0].a.get('href')

print(news_url)

https://www.coindesk.com/tech/2026/05/16/the-usd293-million-kelpdao-hack-shows-why-defi-is-finally-being-forced-to-grow-up

In [ ]:
date_data = rows[0].td.text.strip().split()

print(date_data)

['May-16-26', '09:00AM']

In [ ]:
if len(date_data) == 1:

    news_date = "Today"

    news_time = date_data[0]

else:

    news_date = date_data[0]

    news_time = date_data[1]

print(news_date)

print(news_time)

May-16-26
09:00AM

In [ ]:
news_time = datetime.strptime(

    news_time,

    "%I:%M%p"

).strftime("%H:%M:%S")

print(news_time)

09:00:00

In [ ]:
news_data = []

In [ ]:
news_data.append([

    ticker,

    news_date,

    news_time,

    headline,

    source,

    news_url

])

print(news_data)

[['ETHUSD', 'May-16-26', '09:00:00', 'the $293 million kelpdao hack shows why defi is finally being forced to grow up', 'coindesk', 'https://www.coindesk.com/tech/2026/05/16/the-usd293-million-kelpdao-hack-shows-why-defi-is-finally-being-forced-to-grow-up']]

In [ ]:
news_data = []

In [ ]:
news_data = []

for stock in stocks:

    # Extract Values
    industry = stock[0]

    ticker = stock[1]

    company_name = stock[2]

    print("Pulling Data For:", ticker)

    # Delay
    time.sleep(2)

    # Dynamic URL
    if ticker in ['BTCUSD', 'ETHUSD']:

        url = f"https://finviz.com/crypto_charts.ashx?t={ticker}&p=d"

    else:

        url = f"https://finviz.com/quote.ashx?t={ticker}"

    print(url)

    # Headers
    headers = {

        "User-Agent": (
            "Mozilla/5.0 "
            "(Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 "
            "(KHTML, like Gecko) "
            "Chrome/120.0.0.0 Safari/537.36"
        )
    }

    # Request
    response = requests.get(

        url,

        headers=headers
    )

    print("Status Code:", response.status_code)

    # Skip Failed Requests
    if response.status_code != 200:

        print("Failed:", ticker)

        continue

    # BeautifulSoup
    soup = BeautifulSoup(

        response.text,

        'html.parser'
    )

    # Find News Table
    news_table = soup.find(

        'table',

        id='news-table'
    )

    # Skip If No Table
    if news_table is None:

        print("No News Found")

        continue

    # Extract Rows
    rows = news_table.findAll('tr')

    print("Rows Found:", len(rows))

    # Loop Through Rows
    for row in rows:

        try:

            # Headline
            headline = row.a.text.strip().lower()

            # URL
            news_url = row.a.get('href')

            # Source
            source = row.span.text.strip().lower()

            source = re.sub(

                r"[()]",

                "",

                source
            )

            # Date & Time
            date_data = row.td.text.strip().split()

            if len(date_data) == 1:

                news_date = "Today"

                news_time = date_data[0]

            else:

                news_date = date_data[0]

                news_time = date_data[1]

            # Convert Time
            try:

                news_time = datetime.strptime(

                    news_time,

                    "%I:%M%p"

                ).strftime("%H:%M:%S")

            except:

                pass

            # Store Data
            news_data.append([

                industry,

                ticker,

                company_name,

                news_date,

                news_time,

                headline,

                source,

                news_url

            ])

        except Exception as e:

            print("Error:", e)

            continue

# Create DataFrame
columns = [

    'industry',
    'ticker',
    'company_name',
    'date',
    'time',
    'headline',
    'source',
    'url'

]

df = pd.DataFrame(

    news_data,

    columns=columns
)

# Check Output
print(df.shape)

df.head()

Pulling Data For: NVDA
https://finviz.com/quote.ashx?t=NVDA
Status Code: 200

/tmp/ipykernel_5055/2610248921.py:81: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  rows = news_table.findAll('tr')

Rows Found: 103
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Pulling Data For: AMD
https://finviz.com/quote.ashx?t=AMD
Status Code: 200
Rows Found: 103
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Pulling Data For: INTC
https://finviz.com/quote.ashx?t=INTC
Status Code: 200
Rows Found: 103
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Pulling Data For: JPM
https://finviz.com/quote.ashx?t=JPM
Status Code: 200
Rows Found: 103
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Pulling Data For: BAC
https://finviz.com/quote.ashx?t=BAC
Status Code: 200
Rows Found: 103
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Pulling Data For: GS
https://finviz.com/quote.ashx?t=GS
Status Code: 200
Rows Found: 103
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Pulling Data For: XOM
https://finviz.com/quote.ashx?t=XOM
Status Code: 200
Rows Found: 103
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Pulling Data For: CVX
https://finviz.com/quote.ashx?t=CVX
Status Code: 200
Rows Found: 103
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Pulling Data For: COP
https://finviz.com/quote.ashx?t=COP
Status Code: 200
Rows Found: 103
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Pulling Data For: PFE
https://finviz.com/quote.ashx?t=PFE
Status Code: 200
Rows Found: 103
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Pulling Data For: JNJ
https://finviz.com/quote.ashx?t=JNJ
Status Code: 200
Rows Found: 103
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Pulling Data For: MRK
https://finviz.com/quote.ashx?t=MRK
Status Code: 200
Rows Found: 103
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Pulling Data For: AMZN
https://finviz.com/quote.ashx?t=AMZN
Status Code: 200
Rows Found: 103
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Pulling Data For: WMT
https://finviz.com/quote.ashx?t=WMT
Status Code: 200
Rows Found: 103
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Pulling Data For: COST
https://finviz.com/quote.ashx?t=COST
Status Code: 200
Rows Found: 103
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Error: 'NoneType' object has no attribute 'text'
Pulling Data For: BTCUSD
https://finviz.com/crypto_charts.ashx?t=BTCUSD&p=d
Status Code: 200
Rows Found: 100
Pulling Data For: ETHUSD
https://finviz.com/crypto_charts.ashx?t=ETHUSD&p=d
Status Code: 200
Rows Found: 100
(1700, 8)

,industry,ticker,company_name,date,time,headline,source,url
0,Technology – Semiconductor & AI Industry,NVDA,NVIDIA,Today,08:59:00,"nvidia, retailer reports to shed light on ai b...",reuters,https://finance.yahoo.com/markets/stocks/artic...
1,Technology – Semiconductor & AI Industry,NVDA,NVIDIA,Today,06:43:00,'this is borderline mania': wall street sees b...,yahoo finance,https://finance.yahoo.com/markets/article/this...
2,Technology – Semiconductor & AI Industry,NVDA,NVIDIA,Today,06:42:00,"investors eye nvidia, bond yields, and the nex...",yahoo finance,https://finance.yahoo.com/news/investors-eye-n...
3,Technology – Semiconductor & AI Industry,NVDA,NVIDIA,Today,06:00:00,what to expect in markets this week: nvidia ea...,investopedia,https://finance.yahoo.com/m/6a3ba5ae-726e-31a6...
4,Technology – Semiconductor & AI Industry,NVDA,NVIDIA,May-16-26,16:17:00,the haves and have nots of the ai gold rush,techcrunch,https://finance.yahoo.com/sectors/technology/a...

In [ ]:
df = df.drop_duplicates(

    subset=['ticker', 'headline']
)

df = df.reset_index(drop=True)

In [ ]:
print(df.shape)

df.head()

(1692, 8)

,industry,ticker,company_name,date,time,headline,source,url
0,Technology – Semiconductor & AI Industry,NVDA,NVIDIA,Today,08:59:00,"nvidia, retailer reports to shed light on ai b...",reuters,https://finance.yahoo.com/markets/stocks/artic...
1,Technology – Semiconductor & AI Industry,NVDA,NVIDIA,Today,06:43:00,'this is borderline mania': wall street sees b...,yahoo finance,https://finance.yahoo.com/markets/article/this...
2,Technology – Semiconductor & AI Industry,NVDA,NVIDIA,Today,06:42:00,"investors eye nvidia, bond yields, and the nex...",yahoo finance,https://finance.yahoo.com/news/investors-eye-n...
3,Technology – Semiconductor & AI Industry,NVDA,NVIDIA,Today,06:00:00,what to expect in markets this week: nvidia ea...,investopedia,https://finance.yahoo.com/m/6a3ba5ae-726e-31a6...
4,Technology – Semiconductor & AI Industry,NVDA,NVIDIA,May-16-26,16:17:00,the haves and have nots of the ai gold rush,techcrunch,https://finance.yahoo.com/sectors/technology/a...

In [ ]:
today_date = datetime.today().strftime('%b-%d-%y')

df['date'] = df['date'].replace(

    'Today',

    today_date
)

In [ ]:
df['date'] = pd.to_datetime(

    df['date'],

    format='%b-%d-%y',

    errors='coerce'
)

In [ ]:
df['date'] = df['date'].ffill()

In [ ]:
df[['ticker', 'date']].head(10)

  ticker       date
0   NVDA 2026-05-17
1   NVDA 2026-05-17
2   NVDA 2026-05-17
3   NVDA 2026-05-17
4   NVDA 2026-05-16
5   NVDA 2026-05-17
6   NVDA 2026-05-17
7   NVDA 2026-05-17
8   NVDA 2026-05-17
9   NVDA 2026-05-17

In [ ]:
df['time'] = pd.to_datetime(

    df['time'],

    format='%H:%M:%S',

    errors='coerce'
)

In [ ]:
df['year'] = df['date'].dt.year

df['month'] = df['date'].dt.month

df['month_name'] = df['date'].dt.month_name()

df['quarter'] = df['date'].dt.quarter

df['day'] = df['date'].dt.day

df['weekday'] = df['date'].dt.day_name()

In [ ]:
df['hour'] = df['time'].dt.hour

df['minute'] = df['time'].dt.minute

In [ ]:
market_session = []

for hour in df['hour']:

    if hour < 9:

        market_session.append('Pre-Market')

    elif hour < 16:

        market_session.append('Market Hours')

    else:

        market_session.append('After Market')

df['market_session'] = market_session

In [ ]:
crypto_list = ['BTCUSD', 'ETHUSD']

is_crypto = []

for ticker in df['ticker']:

    if ticker in crypto_list:

        is_crypto.append(True)

    else:

        is_crypto.append(False)

df['is_crypto'] = is_crypto

In [ ]:
clean_headlines = []

for text in df['headline']:

    cleaned = re.sub(

        r'[^a-zA-Z\s]',

        '',

        text
    )

    cleaned = cleaned.lower()

    cleaned = cleaned.strip()

    clean_headlines.append(cleaned)

df['clean_headline'] = clean_headlines

In [ ]:
df[[

    'ticker',

    'headline',

    'clean_headline'

]].head()

,ticker,headline,clean_headline
0,NVDA,"nvidia, retailer reports to shed light on ai b...",nvidia retailer reports to shed light on ai bo...
1,NVDA,'this is borderline mania': wall street sees b...,this is borderline mania wall street sees bubb...
2,NVDA,"investors eye nvidia, bond yields, and the nex...",investors eye nvidia bond yields and the next ...
3,NVDA,what to expect in markets this week: nvidia ea...,what to expect in markets this week nvidia ear...
4,NVDA,the haves and have nots of the ai gold rush,the haves and have nots of the ai gold rush

In [ ]:
df

,industry,ticker,company_name,date,time,headline,source,url,year,month,month_name,quarter,day,weekday,hour,minute,market_session,is_crypto,clean_headline
0,Technology – Semiconductor & AI Industry,NVDA,NVIDIA,2026-05-17,1900-01-01 08:59:00,"nvidia, retailer reports to shed light on ai b...",reuters,https://finance.yahoo.com/markets/stocks/artic...,2026,5,May,2,17,Sunday,8,59,Pre-Market,False,nvidia retailer reports to shed light on ai bo...
1,Technology – Semiconductor & AI Industry,NVDA,NVIDIA,2026-05-17,1900-01-01 06:43:00,'this is borderline mania': wall street sees b...,yahoo finance,https://finance.yahoo.com/markets/article/this...,2026,5,May,2,17,Sunday,6,43,Pre-Market,False,this is borderline mania wall street sees bubb...
2,Technology – Semiconductor & AI Industry,NVDA,NVIDIA,2026-05-17,1900-01-01 06:42:00,"investors eye nvidia, bond yields, and the nex...",yahoo finance,https://finance.yahoo.com/news/investors-eye-n...,2026,5,May,2,17,Sunday,6,42,Pre-Market,False,investors eye nvidia bond yields and the next ...
3,Technology – Semiconductor & AI Industry,NVDA,NVIDIA,2026-05-17,1900-01-01 06:00:00,what to expect in markets this week: nvidia ea...,investopedia,https://finance.yahoo.com/m/6a3ba5ae-726e-31a6...,2026,5,May,2,17,Sunday,6,0,Pre-Market,False,what to expect in markets this week nvidia ear...
4,Technology – Semiconductor & AI Industry,NVDA,NVIDIA,2026-05-16,1900-01-01 16:17:00,the haves and have nots of the ai gold rush,techcrunch,https://finance.yahoo.com/sectors/technology/a...,2026,5,May,2,16,Saturday,16,17,After Market,False,the haves and have nots of the ai gold rush
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1687,Crypto,ETHUSD,Ethereum,2026-02-26,1900-01-01 16:15:00,"ethereum price path to $10,000 now hinges on s...",cryptoslate,https://cryptoslate.com/can-ethereums-strawmap...,2026,2,February,1,26,Thursday,16,15,After Market,True,ethereum price path to now hinges on seven up...
1688,Crypto,ETHUSD,Ethereum,2026-05-17,1900-01-01 15:33:00,here is why ethereum's bold new plan could mak...,coindesk,https://www.coindesk.com/news-analysis/2026/02...,2026,5,May,2,17,Sunday,15,33,Market Hours,True,here is why ethereums bold new plan could make...
1689,Crypto,ETHUSD,Ethereum,2026-05-17,1900-01-01 13:14:00,vitalik buterin unveils ethereum roadmap to co...,coindesk,https://www.coindesk.com/tech/2026/02/26/vital...,2026,5,May,2,17,Sunday,13,14,Market Hours,True,vitalik buterin unveils ethereum roadmap to co...
1690,Crypto,ETHUSD,Ethereum,2026-05-17,1900-01-01 10:34:00,the protocol: blockchain sleuth zachxbt allege...,coindesk,https://www.coindesk.com/tech/2026/02/26/the-p...,2026,5,May,2,17,Sunday,10,34,Market Hours,True,the protocol blockchain sleuth zachxbt alleges...
1691,Crypto,ETHUSD,Ethereum,2026-05-17,1900-01-01 09:00:00,metamask expands debit card across u.s. after ...,coindesk,https://www.coindesk.com/business/2026/02/26/m...,2026,5,May,2,17,Sunday,9,0,Market Hours,True,metamask expands debit card across us after ye...

In [ ]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

True

In [ ]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [ ]:
sia = SentimentIntensityAnalyzer()

In [ ]:
vader_scores = []

In [ ]:
for text in df['clean_headline']:

    score = sia.polarity_scores(text)

    compound_score = score['compound']

    vader_scores.append(compound_score)

In [ ]:
df['vader_score'] = vader_scores

In [ ]:
df[[

    'headline',

    'vader_score'

]].head()

                                            headline  vader_score
0  nvidia, retailer reports to shed light on ai b...       0.0000
1  'this is borderline mania': wall street sees b...       0.6486
2  investors eye nvidia, bond yields, and the nex...       0.0000
3  what to expect in markets this week: nvidia ea...       0.0000
4        the haves and have nots of the ai gold rush       0.0000

In [ ]:
sentiment_labels = []

In [ ]:
for score in df['vader_score']:

    if score >= 0.50:

        sentiment_labels.append('Very Positive')

    elif score >= 0.05:

        sentiment_labels.append('Positive')

    elif score > -0.05:

        sentiment_labels.append('Neutral')

    elif score > -0.50:

        sentiment_labels.append('Negative')

    else:

        sentiment_labels.append('Very Negative')

In [ ]:
df['vader_sentiment'] = sentiment_labels

In [ ]:
df[[

    'headline',

    'vader_score',

    'vader_sentiment'

]].head()

,headline,vader_score,vader_sentiment
0,"nvidia, retailer reports to shed light on ai b...",0.0000,Neutral
1,'this is borderline mania': wall street sees b...,0.6486,Very Positive
2,"investors eye nvidia, bond yields, and the nex...",0.0000,Neutral
3,what to expect in markets this week: nvidia ea...,0.0000,Neutral
4,the haves and have nots of the ai gold rush,0.0000,Neutral

In [ ]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

In [ ]:
from transformers import pipeline

In [ ]:
bert_classifier = pipeline(

    "sentiment-analysis"
)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

In [ ]:
bert_sentiments = []

bert_scores = []

bert_sentiment_5class = []

In [ ]:
for text in df['clean_headline']:

    result = bert_classifier(text)

    label = result[0]['label']

    score = result[0]['score']

    bert_sentiments.append(label)

    bert_scores.append(score)

    # Positive
    if label == 'POSITIVE':

        if score >= 0.95:

            bert_sentiment_5class.append('Very Positive')

        elif score >= 0.75:

            bert_sentiment_5class.append('Positive')

        else:

            bert_sentiment_5class.append('Neutral')

    # Negative
    else:

        if score >= 0.95:

            bert_sentiment_5class.append('Very Negative')

        elif score >= 0.75:

            bert_sentiment_5class.append('Negative')

        else:

            bert_sentiment_5class.append('Neutral')

In [ ]:
df['bert_sentiment'] = bert_sentiments

df['bert_score'] = bert_scores

df['bert_sentiment_5class'] = bert_sentiment_5class

In [ ]:
df[[

    'headline',

    'bert_sentiment',

    'bert_score',

    'bert_sentiment_5class'

]].head()

,headline,bert_sentiment,bert_score,bert_sentiment_5class
0,"nvidia, retailer reports to shed light on ai b...",POSITIVE,0.736720,Neutral
1,'this is borderline mania': wall street sees b...,NEGATIVE,0.997134,Very Negative
2,"investors eye nvidia, bond yields, and the nex...",POSITIVE,0.989322,Very Positive
3,what to expect in markets this week: nvidia ea...,NEGATIVE,0.931571,Negative
4,the haves and have nots of the ai gold rush,NEGATIVE,0.969629,Very Negative

In [ ]:
overall_sentiment = df['vader_sentiment'].value_counts()

print(overall_sentiment)

vader_sentiment
Neutral          709
Positive         416
Negative         270
Very Positive    178
Very Negative    119
Name: count, dtype: int64

In [ ]:
ticker_sentiment = pd.crosstab(

    df['ticker'],

    df['vader_sentiment']
)

print(ticker_sentiment)

vader_sentiment  Negative  Neutral  Positive  Very Negative  Very Positive
ticker
AMD                    15       42        28              1             14
AMZN                   23       29        40              2              6
BAC                    18       37        23              6             16
BTCUSD                 21       42        19              9              9
COP                    13       38        28             15              6
COST                   13       57        20              3              6
CVX                    14       33        25             17             11
ETHUSD                 23       34        27              9              7
GS                     10       48        20              7             15
INTC                   17       37        24              2             14
JNJ                    13       44        25              3             15
JPM                    15       42        28              7              8
MRK                     9       50        22             14              5
NVDA                   15       52        22              2              9
PFE                    18       39        23              5             15
WMT                    15       55        16              3             10
XOM                    18       30        26             14             12

In [ ]:
df.to_excel(

    "final_sentiment_analysis.xlsx",

    index=False
)

In [ ]:
from google.colab import files

files.download(

    "final_sentiment_analysis.xlsx"
)